### ISSUE TITLE
Error with Radarr Api for Request Moovie

### ISSUE THREAD

**Issue by GaetanPTX** [aleksilassila/reiverr#64] opened 2023-08-15 11:29 UTC
Hello, when I click on the "+" button to add a movie, I have a 404 error on the Radarr api.

All other buttons work and when I download a movie from radarr directly it works

![image](https://github.com/aleksilassila/reiverr/assets/51859391/5d46f86a-f603-464f-8fae-2bf2c40ce30d)

**Comment by aleksilassila** [comment] 2023-08-15 11:58
Thanks, I believe I found the cause. Will be fixed in the next release.

**Comment by GaetanPTX** [comment] 2023-08-15 12:36
I still have the error with version 0.4.0

**Closed** 2023-08-15 12:49 UTC
