### ISSUE TITLE
Missing images on Discovery tab

### ISSUE THREAD

**Issue by TomFaulkner** [aleksilassila/reiverr#44] opened 2023-08-11 21:01 UTC
I don't see the images in the git repo.

```
reiverr               | Error: Not found: /genres/documentary.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/drama.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/family.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/fantasy.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/history.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/horror.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               | Error: Not found: /genres/music.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/mystery.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/romance.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/scienceFiction.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/tvMovie.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               | Error: Not found: /genres/thriller.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/war.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
reiverr               |     at runNextTicks (node:internal/process/task_queues:60:5)
reiverr               |     at process.processImmediate (node:internal/timers:447:9)
reiverr               | Error: Not found: /genres/western.jpg
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr               |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr               |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr               |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
```

**Comment by aleksilassila** [comment] 2023-08-13 11:16
Duplicate of #50, these errors are due to some of the genre images not being coded in yet

**Closed** 2023-08-13 11:16 UTC
